# The Basics
NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually number), all the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In example pictured below, the array has rank 2(it is 2-dimensional). The first dimension(axis) has a length of 2, the second dimension has a length of 3.

<code>[[ 1., 0., 0.],
        [ 0., 1., 2.]]</code>
 
Numpy's array class is called <code>ndarray</code>. It is also known by the alias <code>array</code>. Note that <code>numpy.array</code> is not the same as the Standard Python Library class <code>array.array</code>, which only handles one-dimensional arrays and offers less funcitonality. The more important attributes of an <code>ndarray</code> object are:

#### ndarray.ndim
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as <code>rank</code>.

#### ndarray.shape
the size of the array. This is a tuple of the integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, <code>shape</code> will be <code>(n, m)</code>. The length of the <code>shape</code> tuple is therefore the rank, or the number of dimensions, <code>ndim</code>.

#### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of <code>shape</code>.

#### ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16 and numpy.float64 are some exmaples.

#### ndarray.itemsize
the size in bytes of each element of the array. For example, an array of the elements of the type <code>float64</code> has <code>itemsize</code> 8 (=64/8), while one of the type <code>complex32</code> has <code>itemsize</code> 4 (32/8). It is equivalent to <code>ndarray.dtype.itemsize</code>.
## An Example

In [2]:
from numpy import *
a = arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

## Array Creation
There are several ways to create arrays.
For example, you can create an array from a regular python list or tuple using the <code>array</code> function. The type of the resulting array is deduced from the type of the elements in the sequences. 

In [11]:
a = array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b = array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

A frequent error consists in calling <code>array</code> with multiple numeric arguments, rather than providing a signle list of numbers as an argument.

<code>
a = array(1, 2, 3, 4)    # WRONG
a = array([1, 2, 3, 4])  # RIGHT
</code>

<code>array</code> transforms sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [14]:
b = array([(1.5, 2, 3), (4, 5, 6), (7, 8, 9)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ]])

The type of the array can also be explicitely specified at the creation time:

In [15]:
c = array([[1,2], [3,4]], dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function <code>zeros</code> creates an array full of zeros, the function <code>ones</code> creates an array full of ones, and the function <code>empty</code> creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the cerates array is <code>float64</code>

In [16]:
zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
ones((2,3,4), dtype=int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
empty((2,3))

array([[ -3.10503618e+231,   2.00389547e+000,   2.23059525e-314],
       [  2.25349590e-314,   0.00000000e+000,   4.17201348e-309]])

To create sequences of numbers, NumPy provides a function analogous to <code>range</code> that returns arrays instead of lists

In [19]:
arange(10, 30, 5)

array([10, 15, 20, 25])

In [20]:
arange(0, 2, 0.3)     # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [21]:
arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

When <code>arange</code> is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is ususally better to use the function linspace that receives as an argument the number of elements that we want, instead of the step.

In [22]:
linspace(0, 2, 9)   # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [23]:
x = linspace(0, 2*pi, 100)   # useful to evaluate function at lots of points
f = sin(x)

## Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:
<ul>
  <li>the last axis is printed from left to right,</li>
  <li>the second-to-last is printed from top to bottom,</li>
  <li>the rest are also printed from top to bottom, with each slice separated from the next by an empty line.</li>
</ul>
One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [24]:
a = arange(6)                   #1d array
print(a)

[0 1 2 3 4 5]


In [25]:
b = arange(12).reshape(4,3)     #2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
c = arange(24).reshape(2,3,4)   #3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [27]:
a = arange(100).reshape(5,2,2,5)
a

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]],


       [[[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]],


       [[[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69]],

        [[70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]]],


       [[[80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89]],

        [[90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

More on <code>reshape</code> below
If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners.

In [28]:
print(arange(100))
print(arange(100).reshape(10,10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


To disable this behavior and force NumPy to print the entire array, you can change the printing options using <code>set_printoptions</code>.

In [1364]:
set_printoptions(threshold=nan)

## Basic Operations
Arithmetic operators on arrays apply <code>elementwise</code>. A new array is created and filled with the default.

In [1365]:
a = array([20,30,40,50])
b = arange(4)
b

array([0, 1, 2, 3])

In [1366]:
c = a-b
c

array([20, 29, 38, 47])

In [1367]:
b**2

array([0, 1, 4, 9])

In [1368]:
10*sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [1369]:
a<35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the <code>dot</code> function or creating <code>matrix</code> objects (see matrix section of this tutorial)

In [1370]:
A = array([[1,1],
		   [0,1]])
B = array([[2,0],
		   [3,4]])
A*B                 # elementwise product

array([[2, 0],
       [0, 4]])

In [1371]:
dot(A,B)            # matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and \*=, act in place to modify an existing array rather than create a new one.

In [1372]:
a = ones([2,3], dtype=int)
b = random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [1373]:
b += a
b

array([[ 3.54181415,  3.20840369,  3.12960246],
       [ 3.9661683 ,  3.57490832,  3.90164605]])

In [1374]:
# a += b     # error can't cast float to integer

When oprerating with arrays of different types, the type of the resulting array corresponds to the more general or precise one(a behavior known as upcasting)

In [1375]:
a = ones(3, dtype=int32)
b = linspace(0,pi,3)
b.dtype.name

'float64'

In [1376]:
c = a+b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [1377]:
c.dtype.name

'float64'

In [1378]:
d = exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [1379]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the <code>ndarray</code> class.

In [1380]:
a = random.random((2,3))
a

array([[ 0.47680579,  0.42278532,  0.5641703 ],
       [ 0.57520167,  0.01912037,  0.83165464]])

In [1381]:
a.sum()

2.8897380884445281

In [1382]:
a.min()

0.019120374127867712

In [1383]:
a.max()

/Users/shubhankar/IdeaProjects/anaconda/lib/python3.6/site-packages/IPython/core/displayhook.py:260: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  'Flushing oldest {cull_count} entries.'.format(sz=sz, cull_count=cull_count))


0.83165463617950197

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the <code>axis</code> parameter you can apply an operation along the specified axis of an array:

In [1384]:
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [1385]:
b.sum(axis=0)       # sum of each column

array([12, 15, 18, 21])

In [1386]:
b.min(axis=0)       # min in each column

array([0, 1, 2, 3])

In [1387]:
b.cumsum(axis=1)    # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal Functions
NumPy provides familier mathematical functions such as sin, cos and exp. In NumPy, these are called "universal funtions"(<code>ufunc</code>). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [1388]:
B = arange(3)
B

array([0, 1, 2])

In [1389]:
exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [1390]:
sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [1391]:
C = array([2., -1., 4.])
add(B, C)

array([ 2.,  0.,  6.])

## Indexing, Slicing and Iterating
<b>One-dimensional</b> arrays can be indexed, cliced and iterated over much like lists and other Python sequences.

In [1392]:
a = arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [1393]:
a[2]

8

In [1394]:
a[2:5]

array([ 8, 27, 64])

In [1395]:
a[:6:2] = -1000  # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [1396]:
a[::-1]          # reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [1397]:
for i in a:
    print(i**(1/3))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/shubhankar/IdeaProjects/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


<b>Multi-dimensional</b> arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [1398]:
def f(x,y):
	return(10*x+y)
b = fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [1399]:
print(fromfunction(lambda i,j: i + j, (3,3), dtype=int))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [1400]:
b[0:5,1]     # each row in the second column of b(or simply second column of b)

array([ 1, 11, 21, 31, 41])

In [1401]:
b[:,1]       # equivalent to previous example

array([ 1, 11, 21, 31, 41])

In [1402]:
b[1:3,:]     # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices.

In [1403]:
b[-1]        # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in <code>b[i]</code> is treated as an <code>i</code> followed by as many instances of <code>:</code> as needed to represent the remaining axes. NumPy also allows you to write this using dots as <code>b[i,...]</code>.
The <b>dots</b>(...) represent as many colons as needed to produce a complete indexing tuple. For example, if <code>x</code> is a rank 5 array (i.e., it has 5 axes), then
<ul>
	<li><code>x[1,2,...]</code> is equivalent to <code>x[1,2,:,:,:]</code>,</li>
	<li><code>x[...,3]</code> to <code>x[:,:,:,:,3]</code> and</li>
	<li><code>x[4,...,5,:]</code> to <code>x[4,:,:,5,:]</code>.</li>

In [1404]:
x = arange(720).reshape(2,3,4,5,6)
x

array([[[[[  0,   1,   2,   3,   4,   5],
          [  6,   7,   8,   9,  10,  11],
          [ 12,  13,  14,  15,  16,  17],
          [ 18,  19,  20,  21,  22,  23],
          [ 24,  25,  26,  27,  28,  29]],

         [[ 30,  31,  32,  33,  34,  35],
          [ 36,  37,  38,  39,  40,  41],
          [ 42,  43,  44,  45,  46,  47],
          [ 48,  49,  50,  51,  52,  53],
          [ 54,  55,  56,  57,  58,  59]],

         [[ 60,  61,  62,  63,  64,  65],
          [ 66,  67,  68,  69,  70,  71],
          [ 72,  73,  74,  75,  76,  77],
          [ 78,  79,  80,  81,  82,  83],
          [ 84,  85,  86,  87,  88,  89]],

         [[ 90,  91,  92,  93,  94,  95],
          [ 96,  97,  98,  99, 100, 101],
          [102, 103, 104, 105, 106, 107],
          [108, 109, 110, 111, 112, 113],
          [114, 115, 116, 117, 118, 119]]],


        [[[120, 121, 122, 123, 124, 125],
          [126, 127, 128, 129, 130, 131],
          [132, 133, 134, 135, 136, 137],
          [138, 139, 140

In [1405]:
x[...,3]

array([[[[  3,   9,  15,  21,  27],
         [ 33,  39,  45,  51,  57],
         [ 63,  69,  75,  81,  87],
         [ 93,  99, 105, 111, 117]],

        [[123, 129, 135, 141, 147],
         [153, 159, 165, 171, 177],
         [183, 189, 195, 201, 207],
         [213, 219, 225, 231, 237]],

        [[243, 249, 255, 261, 267],
         [273, 279, 285, 291, 297],
         [303, 309, 315, 321, 327],
         [333, 339, 345, 351, 357]]],


       [[[363, 369, 375, 381, 387],
         [393, 399, 405, 411, 417],
         [423, 429, 435, 441, 447],
         [453, 459, 465, 471, 477]],

        [[483, 489, 495, 501, 507],
         [513, 519, 525, 531, 537],
         [543, 549, 555, 561, 567],
         [573, 579, 585, 591, 597]],

        [[603, 609, 615, 621, 627],
         [633, 639, 645, 651, 657],
         [663, 669, 675, 681, 687],
         [693, 699, 705, 711, 717]]]])

In [1406]:
c = array([[[0, 1, 2],         # a 3D array (two stacked 2D arrays)
		   [10, 12, 13]],
		  [[100, 101, 102],
		  [110, 112, 113]]])
c.shape

(2, 2, 3)

In [1407]:
c[1,...]                       # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [1408]:
c[...,2]                       # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

<b>Iterating</b> over multidimensional arrays is done with respect to the first axis:

In [1409]:
for row in b:
	print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operatoin on each element in the array, one can use the <code>flat</code> attribute which is an iterator over all the elements of the array:

In [1410]:
for element in b.flat:
	print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulation
## Changing the shape of an array
The array has a shape given by the number of elements along each axis:

In [1411]:
a = floor(10*random.random((3,4)))
a

array([[ 4.,  1.,  2.,  7.],
       [ 1.,  7.,  0.,  8.],
       [ 7.,  5.,  7.,  4.]])

In [1412]:
a.shape

(3, 4)

The shape of an array can be changed with various commands:

In [1413]:
a.ravel() # flatten the array

array([ 4.,  1.,  2.,  7.,  1.,  7.,  0.,  8.,  7.,  5.,  7.,  4.])

In [1414]:
a.shape

(3, 4)

In [1415]:
a.transpose()    # or a.T computes transpose

array([[ 4.,  1.,  7.],
       [ 1.,  7.,  5.],
       [ 2.,  0.,  7.],
       [ 7.,  8.,  4.]])

The order of the elements in the array resulting from ravel( ) is normally "C-style", that is, the rightmost index "changes the fastest", so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as "C-style". NumPy normally creates arrays stored in this order, so ravel( ) will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied, The functions ravel( ) and reshape( ) can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index hanges the fastest.

The <b>reshape</b> function returns its argument with a modified shape, whereas the <b>resize</b> method modifies the array itself.

In [1416]:
a

array([[ 4.,  1.,  2.,  7.],
       [ 1.,  7.,  0.,  8.],
       [ 7.,  5.,  7.,  4.]])

In [1417]:
a.resize((2,6))

In [1418]:
a

array([[ 4.,  1.,  2.,  7.,  1.,  7.],
       [ 0.,  8.,  7.,  5.,  7.,  4.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated.

In [1419]:
a.reshape(3,-1)

array([[ 4.,  1.,  2.,  7.],
       [ 1.,  7.,  0.,  8.],
       [ 7.,  5.,  7.,  4.]])

## Stacking together different arrays
Several arrays can be stacked together along different axes:

In [1420]:
a = floor(10*random.random((2,2)))
a

array([[ 2.,  9.],
       [ 3.,  4.]])

In [1421]:
b = floor(10*random.random((2,2)))
b

array([[ 4.,  4.],
       [ 2.,  3.]])

In [1422]:
vstack((a,b))

array([[ 2.,  9.],
       [ 3.,  4.],
       [ 4.,  4.],
       [ 2.,  3.]])

In [1423]:
hstack((a,b))

array([[ 2.,  9.,  4.,  4.],
       [ 3.,  4.,  2.,  3.]])

The function column_stack stacks 1D arrays as columns into a 2D array. <b>Note:</b> Notice the similarities and differences among column_stack, vstack and hstack.

In [1424]:
c = column_stack((a,b))     # With 2D arrays
c

array([[ 2.,  9.,  4.,  4.],
       [ 3.,  4.,  2.,  3.]])

In [1425]:
c[1,0]

3.0

In [1426]:
a=array([4.,2.])
b=array([2.,8.])
a[:,newaxis]            # This allows to have a 2D columns vector

array([[ 4.],
       [ 2.]])

In [1427]:
column_stack((a[:,newaxis], b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [1428]:
vstack((a[:,newaxis],b[:,newaxis]))   # The behavior of vstack is different

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

The function row_stack, on the other hand, stacks 1D arrays as rows into a 2D array. 

For arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

<b>Note</b>

In complex cases, <code>r\_[]</code> and <code>c\_[]</code> are useful for creating arrays by stacking numbers along axis. They alloe the use of range literals(":"):

In [1429]:
r_[1:4,0,4]

array([1, 2, 3, 0, 4])

When used with arrays as arguments, <code>r\_[]</code> and <code>c\_[]</code> are similar to vstack and hstack in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate.
## Splitting one array into several smaller ones
Using <code>hsplit</code>, you can split an array along gits horizontal axis, either by specifying the number of equally shaped arrays to return, or bu specifying the columns afer which the division should occur:

In [1430]:
a = floor(10*random.random((2,12)))
a

array([[ 1.,  1.,  8.,  7.,  3.,  4.,  7.,  8.,  5.,  1.,  0.,  4.],
       [ 8.,  0.,  1.,  1.,  7.,  9.,  0.,  4.,  9.,  2.,  7.,  0.]])

In [1431]:
hsplit(a,3)        # Split a into 3

[array([[ 1.,  1.,  8.,  7.],
        [ 8.,  0.,  1.,  1.]]), array([[ 3.,  4.,  7.,  8.],
        [ 7.,  9.,  0.,  4.]]), array([[ 5.,  1.,  0.,  4.],
        [ 9.,  2.,  7.,  0.]])]

In [1432]:
hsplit(a,(3,4))     # Split a after the third and the fourth column

[array([[ 1.,  1.,  8.],
        [ 8.,  0.,  1.]]), array([[ 7.],
        [ 1.]]), array([[ 3.,  4.,  7.,  8.,  5.,  1.,  0.,  4.],
        [ 7.,  9.,  0.,  4.,  9.,  2.,  7.,  0.]])]

<code>vsplit()</code> splits along the certical axis, and <code>array_split()</code> allows one to specify along which axis to split.
# Copies and Views
When operating and manupulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:
## No Copy at All
Simple assignments make no copy of array objects or of their data.

In [1433]:
a = arange(12)
b = a            # no object is created
b is a           # a and b are two names gor the same ndarray object

True

In [1434]:
b.shape = 3,4     # changes the shape of a
a.shape

(3, 4)

Python passes mutable objects as references, so function calls make no copy.

In [1435]:
def f(x):
    print(id(x))
id(a)                # id is a unique identifier of an object

4631276240

In [1436]:
f(a)

4631276240


## View or Shallow Copy
Different array objects can share the same data. The <code>view</code> method creates a new array object that looks at the same data.

In [1437]:
c = a.view()
c is a

False

In [1438]:
c.base is a           # c is a view of the data owned by a

True

In [1439]:
c.flags.owndata

False

In [1440]:
c.shape = 2,6         # a's shape doesn't change
a.shape

(3, 4)

In [1441]:
c[0,4] = 1234        # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:

In [1442]:
s = a[:,1:3]
s[:] = 10            # s is a view of s. Note the difference between s=10 and s[:]
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Deep Copy
The <code>copy</code> method makes a copy of the array and its data.

In [1443]:
d = a.copy()                # a new array object with new daa is created
d is a

False

In [1444]:
d.base is a                # d doesn't share anything with a

False

In [1445]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

# Fancy indexing and index tricks
NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices arrays can be indexed by arrays of integers and arrays of booleans.

## Indexing with Arrays of Indices

In [1446]:
a = arange(12)**2        # the first 12 square numbers
i = array([1,1,3,8,5])   # an array of indices
a[i]                     # the elements of a at the positions i

array([ 1,  1,  9, 64, 25])

In [1447]:
j = array([[3,4], [9,7]])     # a bidirectional array of indices
a[j]                          # the same shape as j

array([[ 9, 16],
       [81, 49]])

When the indexed array <code>a</code> is multidimensional, a single array of indices referes to the first dimension of <code>a</code>. The following example shows this behavior by converting an image of labels into a color image using a palette.

In [1448]:
palette = array([[0,0,0],          # black
                [255,0,0],         # red
                [0,255,0],         # green
                [0,0,255],         # blue
                [255,255,255]])    # white
image = array([[0,1,2,0],
              [0,3,4,0]])          # each value corresponds to a color(row) in the palette
palette[image]                     # the (2,4,3) color image

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.

In [1449]:
a = arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [1450]:
i = array([[0,1],         # indices for the first axis(dimension) of a           
          [1,2]])
j = array([[2,1],         # indices for the second axis(dimension)
          [3,3]])

In [1451]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [1452]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [1453]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

You can also use indexing with arrays as a target to assign to:

In [1454]:
a = arange(5)
a

array([0, 1, 2, 3, 4])

In [1455]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

However, when the list of indices contains repetitions, the assignments is done several times, leaving behind the last value.

In [1456]:
a = arange(5)
a[[0,0,2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

This is reasonable enough, but watch out if you want to use Python's += construct, as it may not do what you expect:

In [1457]:
a = arange(5)
a[[0,0,2]] = a[[0,0,2]]+1        # similar to a+= 1
a

array([1, 1, 3, 3, 4])

Even though 0 occurs twice in the list of indices, the 0th element is only incremented once. This is because Python requires "a+=1" to be equivalent to "a=a+1".

## Indexing with Boolean Arrays
When we index arrays with arrays of indices we are providing the list of indices to pick. With boolean indices the approach is different, we explicitly choose which items in the array we want and ones we don't.
The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array.

In [1458]:
a = arange(12).reshape(3,4)
b = a > 4
b                                 # b is a boolean with a's shape

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [1459]:
a[b]                              # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

This property can be useful in assignments:

In [1460]:
a[b] = 0                           # All elements of 'a' higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

## The <code>ix_()</code> function

The <code>ix_()</code> function can be used to combine different vectors so as to obtain the result for each n-tuplet. For example, if you want to compute all the a+b\*x for all the triplets taken from each of the vectors a, b and c:

In [1461]:
a = array([2,3,4,5])
b = array([8,5,4])
c = array([5,4,6,8,3])
ax,bx,cx = ix_(a,b,c)
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [1462]:
bx

array([[[8],
        [5],
        [4]]])

In [1463]:
cx

array([[[5, 4, 6, 8, 3]]])

In [1464]:
ax.shape

(4, 1, 1)

In [1465]:
bx.shape

(1, 3, 1)

In [1466]:
cx.shape

(1, 1, 5)

In [1467]:
result = ax+bx*cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [1468]:
result[3,2,4]

17

In [1469]:
a[3]+b[2]*c[4]

17

# Linear Algebra
See linalg.py in numpy folder for more.

In [1470]:
a = array([[1.0, 2.0], [3.0, 4.0]])
a

array([[ 1.,  2.],
       [ 3.,  4.]])

In [1478]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [1472]:
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [1473]:
u = eye(2)               # unit 2x2 matrix; "eye" represents "I"
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [1474]:
j - array([[0.0, -1.0,], [1.0, 0.0]])
dot(j, j)               # matrix product

array([[ 7,  5],
       [15, 12]])

In [1475]:
trace(u)                # trace

2.0

In [1476]:
y = array([[5.], [7.]])
solve(a,y)

array([[-3.],
       [ 4.]])

In [1477]:
eig(j)

(array([ 0.69722436,  4.30277564]), array([[-0.60889368, -0.3983218 ],
        [ 0.79325185, -0.91724574]]))